spring.datasource.url=jdbc:postgresql://localhost:5432/simulados_bd
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Desabilita JPA
spring.jpa.hibernate.ddl-auto=none
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

# Porta do servidor
server.port=8080

# Logs SQL
logging.level.org.springframework.jdbc=DEBUG




